services:
  minio:
    environment:
      MINIO_KMS_SERVER: ${PROD_MINIO_KMS_SERVER:?set PROD_MINIO_KMS_SERVER}
      MINIO_KMS_ENCLAVE: ${PROD_MINIO_KMS_ENCLAVE:?set PROD_MINIO_KMS_ENCLAVE}
      MINIO_KMS_API_KEY: ${PROD_MINIO_KMS_API_KEY:?set PROD_MINIO_KMS_API_KEY}
      MINIO_KMS_SSE_KEY: ${PROD_MINIO_KMS_SSE_KEY:?set PROD_MINIO_KMS_SSE_KEY}
